name: CI

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules...
      run: git submodule init && git submodule update --init --recursive
    - name: Installing SDL2 via brew...
      run: brew install sdl2
    - name: Listing files...
      run: ls -al
    - name: Building...
      run: ./build.sh macos
    - name: Packing artifact...
    - run: |
        mkdir -p ${{ github.workspace }}/artifact
        cp -r data ${{ github.workspace }}/artifact/
        cp lite ${{ github.workspace }}/artifact/
    - name: Uploading artifact...
      uses: actions/upload-artifact@v2
      with:
        name: lite_macos
        path: artifact
